USE bdPadron;

INSERT INTO taProvincias VALUES (01, "Araba/Álava");
INSERT INTO taProvincias VALUES (02, "Albacete");
INSERT INTO taProvincias VALUES (03, "Alicante/Alacant");
INSERT INTO taProvincias VALUES (04, "Almería");
INSERT INTO taProvincias VALUES (05, "Ávila");
INSERT INTO taProvincias VALUES (06, "Badajoz");
INSERT INTO taProvincias VALUES (07, "Balears, Illes");
INSERT INTO taProvincias VALUES (08, "Barcelona");
INSERT INTO taProvincias VALUES (09, "Burgos");
INSERT INTO taProvincias VALUES (10, "Cáceres");
INSERT INTO taProvincias VALUES (11, "Cádiz");
INSERT INTO taProvincias VALUES (12, "Castellón/Castelló");
INSERT INTO taProvincias VALUES (13, "Ciudad Real");
INSERT INTO taProvincias VALUES (14, "Córdoba");
INSERT INTO taProvincias VALUES (15, "Coruña, A");
INSERT INTO taProvincias VALUES (16, "Cuenca");
INSERT INTO taProvincias VALUES (17, "Girona");
INSERT INTO taProvincias VALUES (18, "Granada");
INSERT INTO taProvincias VALUES (19, "Guadalajara");
INSERT INTO taProvincias VALUES (20, "Gipuzkoa");
INSERT INTO taProvincias VALUES (21, "Huelva");
INSERT INTO taProvincias VALUES (22, "Huesca");
INSERT INTO taProvincias VALUES (23, "Jaén");
INSERT INTO taProvincias VALUES (24, "León");
INSERT INTO taProvincias VALUES (25, "Lleida");
INSERT INTO taProvincias VALUES (26, "Rioja, La");
INSERT INTO taProvincias VALUES (27, "Lugo");
INSERT INTO taProvincias VALUES (28, "Madrid");
INSERT INTO taProvincias VALUES (29, "Málaga");
INSERT INTO taProvincias VALUES (30, "Murcia");
INSERT INTO taProvincias VALUES (31, "Navarra");
INSERT INTO taProvincias VALUES (32, "Ourense");
INSERT INTO taProvincias VALUES (33, "Asturias");
INSERT INTO taProvincias VALUES (34, "Palencia");
INSERT INTO taProvincias VALUES (35, "Palmas, Las");
INSERT INTO taProvincias VALUES (36, "Pontevedra");
INSERT INTO taProvincias VALUES (37, "Salamanca");
INSERT INTO taProvincias VALUES (38, "Santa Cruz de Tenerife");
INSERT INTO taProvincias VALUES (39, "Cantabria");
INSERT INTO taProvincias VALUES (40, "Segovia");
INSERT INTO taProvincias VALUES (41, "Sevilla");
INSERT INTO taProvincias VALUES (42, "Soria");
INSERT INTO taProvincias VALUES (43, "Tarragona");
INSERT INTO taProvincias VALUES (44, "Teruel");
INSERT INTO taProvincias VALUES (45, "Toledo");
INSERT INTO taProvincias VALUES (46, "Valencia/València");
INSERT INTO taProvincias VALUES (47, "Valladolid");
INSERT INTO taProvincias VALUES (48, "Bizkaia");
INSERT INTO taProvincias VALUES (49, "Zamora");
INSERT INTO taProvincias VALUES (50, "Zaragoza");
INSERT INTO taProvincias VALUES (51, "Ceuta");
INSERT INTO taProvincias VALUES (52, "Melilla");
