USE bdPadron;

UPDATE taProvincias SET vaNomProvincia = "Álava" WHERE iCodProvincia = 01;
UPDATE taProvincias SET vaNomProvincia = "Albacete" WHERE iCodProvincia = 02;
UPDATE taProvincias SET vaNomProvincia = "Alicante" WHERE iCodProvincia = 03;
UPDATE taProvincias SET vaNomProvincia = "Almería" WHERE iCodProvincia = 04;
UPDATE taProvincias SET vaNomProvincia = "Ávila" WHERE iCodProvincia = 05;
UPDATE taProvincias SET vaNomProvincia = "Badajoz" WHERE iCodProvincia = 06;
UPDATE taProvincias SET vaNomProvincia = "Baleares" WHERE iCodProvincia = 07;
UPDATE taProvincias SET vaNomProvincia = "Barcelona" WHERE iCodProvincia = 08;
UPDATE taProvincias SET vaNomProvincia = "Burgos" WHERE iCodProvincia = 09;
UPDATE taProvincias SET vaNomProvincia = "Cáceres" WHERE iCodProvincia = 10;
UPDATE taProvincias SET vaNomProvincia = "Cádiz" WHERE iCodProvincia = 11;
UPDATE taProvincias SET vaNomProvincia = "Castellón" WHERE iCodProvincia = 12;
UPDATE taProvincias SET vaNomProvincia = "Ciudad Real" WHERE iCodProvincia = 13;
UPDATE taProvincias SET vaNomProvincia = "Córdoba" WHERE iCodProvincia = 14;
UPDATE taProvincias SET vaNomProvincia = "La Coruña" WHERE iCodProvincia = 15;
UPDATE taProvincias SET vaNomProvincia = "Cuenca" WHERE iCodProvincia = 16;
UPDATE taProvincias SET vaNomProvincia = "Gerona" WHERE iCodProvincia = 17;
UPDATE taProvincias SET vaNomProvincia = "Granada" WHERE iCodProvincia = 18;
UPDATE taProvincias SET vaNomProvincia = "Guadalajara" WHERE iCodProvincia = 19;
UPDATE taProvincias SET vaNomProvincia = "Guipúzcoa" WHERE iCodProvincia = 20;
UPDATE taProvincias SET vaNomProvincia = "Huelva" WHERE iCodProvincia = 21;
UPDATE taProvincias SET vaNomProvincia = "Huesca" WHERE iCodProvincia = 22;
UPDATE taProvincias SET vaNomProvincia = "Jaén" WHERE iCodProvincia = 23;
UPDATE taProvincias SET vaNomProvincia = "León" WHERE iCodProvincia = 24;
UPDATE taProvincias SET vaNomProvincia = "Lérida" WHERE iCodProvincia = 25;
UPDATE taProvincias SET vaNomProvincia = "La Rioja" WHERE iCodProvincia = 26;
UPDATE taProvincias SET vaNomProvincia = "Lugo" WHERE iCodProvincia = 27;
UPDATE taProvincias SET vaNomProvincia = "Madrid" WHERE iCodProvincia = 28;
UPDATE taProvincias SET vaNomProvincia = "Málaga" WHERE iCodProvincia = 29;
UPDATE taProvincias SET vaNomProvincia = "Murcia" WHERE iCodProvincia = 30;
UPDATE taProvincias SET vaNomProvincia = "Navarra" WHERE iCodProvincia = 31;
UPDATE taProvincias SET vaNomProvincia = "Orense" WHERE iCodProvincia = 32;
UPDATE taProvincias SET vaNomProvincia = "Asturias" WHERE iCodProvincia = 33;
UPDATE taProvincias SET vaNomProvincia = "Palencia" WHERE iCodProvincia = 34;
UPDATE taProvincias SET vaNomProvincia = "Las Palmas" WHERE iCodProvincia = 35;
UPDATE taProvincias SET vaNomProvincia = "Pontevedra" WHERE iCodProvincia = 36;
UPDATE taProvincias SET vaNomProvincia = "Salamanca" WHERE iCodProvincia = 37;
UPDATE taProvincias SET vaNomProvincia = "Santa Cruz" WHERE iCodProvincia = 38;
UPDATE taProvincias SET vaNomProvincia = "Cantabria" WHERE iCodProvincia = 39;
UPDATE taProvincias SET vaNomProvincia = "Segovia" WHERE iCodProvincia = 40;
UPDATE taProvincias SET vaNomProvincia = "Sevilla" WHERE iCodProvincia = 41;
UPDATE taProvincias SET vaNomProvincia = "Soria" WHERE iCodProvincia = 42;
UPDATE taProvincias SET vaNomProvincia = "Tarragona" WHERE iCodProvincia = 43;
UPDATE taProvincias SET vaNomProvincia = "Teruel" WHERE iCodProvincia = 44;
UPDATE taProvincias SET vaNomProvincia = "Toledo" WHERE iCodProvincia = 45;
UPDATE taProvincias SET vaNomProvincia = "Valencia" WHERE iCodProvincia = 46;
UPDATE taProvincias SET vaNomProvincia = "Valladolid" WHERE iCodProvincia = 47;
UPDATE taProvincias SET vaNomProvincia = "Vizcaya" WHERE iCodProvincia = 48;
UPDATE taProvincias SET vaNomProvincia = "Zamora" WHERE iCodProvincia = 49;
UPDATE taProvincias SET vaNomProvincia = "Zaragoza" WHERE iCodProvincia = 50;
UPDATE taProvincias SET vaNomProvincia = "Ceuta" WHERE iCodProvincia = 51;
UPDATE taProvincias SET vaNomProvincia = "Melilla" WHERE iCodProvincia = 52;
